import React, { useState } from 'react';
import { Conversation, Folder } from '../types';
import { Plus, MessageSquare, Search, Settings, Trash2, Edit2, Sun, Moon, X, Folder as FolderIcon, FolderPlus, ChevronDown, ChevronRight, FolderOpen, MoveRight, Globe, BookOpen } from 'lucide-react';
import { GoogleHubModal } from './google/GoogleHubModal';

interface SidebarProps { conversations: Conversation[]; folders?: Folder[]; activeId: string | null; onSelectConversation: (id: string) => void; onNewConversation: () => void; onRenameConversation: (id: string) => void; onDeleteConversation: (id: string) => void; onCreateFolder?: (name: string) => void; onRenameFolder?: (id: string, name: string) => void; onDeleteFolder?: (id: string) => void; onToggleFolder?: (id: string) => void; onMoveToFolder?: (conversationId: string, folderId: string | null) => void; onOpenSettings: () => void; onOpenWorld?: () => void; onOpenMemory?: () => void; onOpenWorkspace: () => void; isOpen: boolean; onCloseMobile: () => void; theme: 'dark' | 'light'; onToggleTheme: () => void; }

export const Sidebar: React.FC<SidebarProps> = ({ conversations, folders = [], activeId, onSelectConversation, onNewConversation, onRenameConversation, onDeleteConversation, onCreateFolder, onRenameFolder, onDeleteFolder, onToggleFolder, onMoveToFolder, onOpenSettings, onOpenWorld, onOpenMemory, onOpenWorkspace, isOpen, onCloseMobile, theme, onToggleTheme }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [isCreatingFolder, setIsCreatingFolder] = useState(false);
  const [newFolderName, setNewFolderName] = useState('');
  const [editingFolderId, setEditingFolderId] = useState<string | null>(null);
  const [editingFolderName, setEditingFolderName] = useState('');
  const [movingConvId, setMovingConvId] = useState<string | null>(null);
  const [googleHubOpen, setGoogleHubOpen] = useState(false);
  const filteredConversations = conversations.filter((c) => { if (!searchTerm.trim()) return true; const query = searchTerm.toLowerCase(); return c.title.toLowerCase().includes(query) || c.messages.some((m) => m.content.toLowerCase().includes(query)); });
  const handleCreateFolderSubmit = (e: React.FormEvent) => { e.preventDefault(); if (newFolderName.trim() && onCreateFolder) { onCreateFolder(newFolderName.trim()); setNewFolderName(''); setIsCreatingFolder(false); } };
  const handleRenameFolderSubmit = (id: string) => { if (editingFolderName.trim() && onRenameFolder) { onRenameFolder(id, editingFolderName.trim()); setEditingFolderId(null); setEditingFolderName(''); } };
  const rootConversations = filteredConversations.filter((c) => !c.folderId || !folders.some((f) => f.id === c.folderId));
  const renderConversationItem = (conv: Conversation) => { const isActive = conv.id === activeId; return <div key={conv.id} onClick={() => { onSelectConversation(conv.id); onCloseMobile(); }} className={`group relative flex items-center px-3 py-2 rounded-lg cursor-pointer transition-colors text-xs ${isActive ? 'bg-zinc-800/90 border border-zinc-700/60 text-zinc-100 font-medium' : 'text-zinc-400 hover:bg-zinc-800/50 hover:text-zinc-200'}`}><MessageSquare className={`w-3.5 h-3.5 mr-2.5 shrink-0 ${isActive ? 'text-sky-400' : 'text-zinc-500'}`} /><span className="truncate flex-1 min-w-0">{conv.title || 'New Conversation'}</span><div className={`flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity ${isActive ? 'opacity-100' : ''}`}>{onMoveToFolder && folders.length > 0 && <div className="relative"><button onClick={(e) => { e.stopPropagation(); setMovingConvId(movingConvId === conv.id ? null : conv.id); }} className="p-1 rounded text-zinc-400 hover:text-sky-400 hover:bg-zinc-700/50" title="Move to folder"><MoveRight className="w-3 h-3" /></button>{movingConvId === conv.id && <div onClick={(e) => e.stopPropagation()} className="absolute right-0 top-6 z-50 w-44 bg-zinc-900 border border-zinc-700 rounded-xl p-1.5 shadow-2xl space-y-1 text-xs"><div className="text-[10px] text-zinc-500 font-semibold px-2 py-1">Move To:</div><button onClick={() => { onMoveToFolder(conv.id, null); setMovingConvId(null); }} className="w-full text-left px-2 py-1 rounded-lg hover:bg-zinc-800 text-zinc-300 text-xs truncate">(No Folder)</button>{folders.map((f) => <button key={f.id} onClick={() => { onMoveToFolder(conv.id, f.id); setMovingConvId(null); }} className="w-full text-left px-2 py-1 rounded-lg hover:bg-zinc-800 text-zinc-300 text-xs truncate flex items-center gap-1.5"><FolderIcon className="w-3 h-3 text-sky-400 shrink-0" /><span className="truncate">{f.name}</span></button>)}</div>}</div>}<button onClick={(e) => { e.stopPropagation(); onRenameConversation(conv.id); }} className="p-1 rounded text-zinc-400 hover:text-zinc-200 hover:bg-zinc-700/50" title="Rename"><Edit2 className="w-3 h-3" /></button><button onClick={(e) => { e.stopPropagation(); onDeleteConversation(conv.id); }} className="p-1 rounded text-zinc-400 hover:text-red-400 hover:bg-zinc-700/50" title="Delete"><Trash2 className="w-3 h-3" /></button></div></div>; };
  const handleSettingsClick = () => { onCloseMobile(); onOpenSettings(); };
  const handleGoogleHubClick = () => { onCloseMobile(); setGoogleHubOpen(true); };
  return <><div>{isOpen && <div onClick={onCloseMobile} className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-[90] md:hidden" />}<aside className={`fixed md:static inset-y-0 left-0 w-72 md:w-80 bg-[#121212] border-r border-zinc-800 flex flex-col z-[100] transition-transform duration-300 ease-in-out ${isOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}`}>
    <div className="p-4 border-b border-zinc-800 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-sky-600 flex items-center justify-center text-white font-bold text-xs shadow-md shadow-sky-900/30">E</div><div><h1 className="font-semibold text-zinc-100 text-sm tracking-tight">Elara Assistant</h1><p className="text-[11px] text-zinc-500">Gemini Cybernetic Companion</p></div></div><button onClick={onCloseMobile} className="md:hidden p-1.5 rounded-lg text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800"><X className="w-5 h-5" /></button></div>
    <div className="p-4 pb-2 space-y-2"><div className="flex items-center gap-2"><button onClick={() => { onNewConversation(); onCloseMobile(); }} className="flex-1 py-2.5 px-3 rounded-lg border border-zinc-700 bg-zinc-800/50 hover:bg-zinc-800 flex items-center justify-between transition-colors group text-zinc-100"><span className="text-sm font-medium">New Chat</span><Plus className="w-4 h-4 text-zinc-500 group-hover:text-sky-400 transition-colors" /></button>{onCreateFolder && <button onClick={() => setIsCreatingFolder(!isCreatingFolder)} className="p-2.5 rounded-lg border border-zinc-800 hover:border-zinc-700 bg-zinc-900 hover:bg-zinc-800 text-zinc-400 hover:text-sky-400 transition-colors" title="Create Folder"><FolderPlus className="w-4 h-4" /></button>}</div>{isCreatingFolder && <form onSubmit={handleCreateFolderSubmit} className="p-2 rounded-xl bg-zinc-900 border border-zinc-700 space-y-2"><input type="text" value={newFolderName} onChange={(e) => setNewFolderName(e.target.value)} placeholder="Folder name..." autoFocus className="w-full px-2.5 py-1 text-xs rounded bg-zinc-950 border border-zinc-800 text-zinc-200 focus:outline-none focus:border-sky-500" /><div className="flex items-center justify-end gap-1.5"><button type="button" onClick={() => setIsCreatingFolder(false)} className="px-2 py-1 text-[11px] text-zinc-400 hover:text-zinc-200">Cancel</button><button type="submit" disabled={!newFolderName.trim()} className="px-2.5 py-1 text-[11px] font-medium bg-sky-600 hover:bg-sky-500 text-white rounded disabled:opacity-50">Create</button></div></form>}</div>
    <div className="px-4 pb-2"><div className="relative"><Search className="w-4 h-4 text-zinc-500 absolute left-3 top-2.5" /><input type="text" value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} placeholder="Search conversations..." className="w-full pl-9 pr-3 py-1.5 rounded-lg bg-zinc-900 border border-zinc-800 text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-sky-500/50" /></div></div>
    <div className="text-[11px] font-semibold text-zinc-500 uppercase tracking-wider px-4 mt-2 mb-1 flex items-center justify-between"><span>Conversations</span><span className="text-[10px] font-mono text-zinc-600">{conversations.length}</span></div>
    <div className="flex-1 overflow-y-auto px-3 space-y-1.5 custom-scrollbar">{folders.map((folder) => { const folderConvs = filteredConversations.filter((c) => c.folderId === folder.id); const isExpanded = folder.isExpanded !== false; return <div key={folder.id} className="space-y-1 rounded-xl bg-zinc-900/30 border border-zinc-800/40 p-1"><div onClick={() => onToggleFolder && onToggleFolder(folder.id)} className="group flex items-center justify-between px-2 py-1.5 rounded-lg hover:bg-zinc-800/60 cursor-pointer text-xs text-zinc-300 transition-colors"><div className="flex items-center gap-1.5 truncate flex-1 min-w-0">{isExpanded ? <ChevronDown className="w-3.5 h-3.5 text-zinc-500 shrink-0" /> : <ChevronRight className="w-3.5 h-3.5 text-zinc-500 shrink-0" />}{isExpanded ? <FolderOpen className="w-3.5 h-3.5 text-amber-400 shrink-0" /> : <FolderIcon className="w-3.5 h-3.5 text-amber-400 shrink-0" />}{editingFolderId === folder.id ? <input type="text" value={editingFolderName} onChange={(e) => setEditingFolderName(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') handleRenameFolderSubmit(folder.id); if (e.key === 'Escape') setEditingFolderId(null); }} onBlur={() => handleRenameFolderSubmit(folder.id)} autoFocus onClick={(e) => e.stopPropagation()} className="px-1 py-0.5 text-xs bg-zinc-950 border border-zinc-700 text-zinc-100 rounded focus:outline-none" /> : <span className="font-medium truncate">{folder.name}</span>}<span className="text-[10px] text-zinc-500 font-mono">({folderConvs.length})</span></div><div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity"><button onClick={(e) => { e.stopPropagation(); setEditingFolderId(folder.id); setEditingFolderName(folder.name); }} className="p-1 text-zinc-500 hover:text-zinc-300" title="Rename Folder"><Edit2 className="w-3 h-3" /></button>{onDeleteFolder && <button onClick={(e) => { e.stopPropagation(); onDeleteFolder(folder.id); }} className="p-1 text-zinc-500 hover:text-red-400" title="Delete Folder"><Trash2 className="w-3 h-3" /></button>}</div></div>{isExpanded && <div className="pl-3 space-y-1 border-l border-zinc-800 ml-3">{folderConvs.length === 0 ? <div className="text-[11px] text-zinc-600 px-2 py-1 italic">Empty folder</div> : folderConvs.map((c) => renderConversationItem(c))}</div>}</div>; })}{rootConversations.length > 0 && <div className="space-y-1 pt-1">{folders.length > 0 && <div className="text-[10px] font-semibold text-zinc-600 uppercase tracking-wider px-2 pt-2">Unassigned</div>}{rootConversations.map((c) => renderConversationItem(c))}</div>}{filteredConversations.length === 0 && folders.length === 0 && <div className="text-center py-8 px-4 text-xs text-zinc-500">{searchTerm ? 'No conversations found.' : 'No conversations yet.'}</div>}</div>
    <div className="p-4 border-t border-zinc-800 space-y-2">{onOpenMemory && <button onClick={() => { onOpenMemory(); onCloseMobile(); }} className="w-full flex items-center px-3 py-2 text-amber-400 hover:text-amber-300 hover:bg-amber-950/40 rounded-lg transition-colors text-sm font-medium border border-amber-800/40"><BookOpen className="w-4 h-4 mr-2.5 text-amber-400" /><span>Memory Scratchpad</span></button>}{onOpenWorld && <button onClick={() => { onOpenWorld(); onCloseMobile(); }} className="w-full flex items-center px-3 py-2 text-sky-400 hover:text-sky-300 hover:bg-sky-950/40 rounded-lg transition-colors text-sm font-medium border border-sky-800/40"><Globe className="w-4 h-4 mr-2.5 text-sky-400" /><span>World State & Life</span></button>}<button onClick={() => { onOpenWorkspace(); onCloseMobile(); }} className="w-full flex items-center px-3 py-2 text-emerald-400 hover:text-emerald-300 hover:bg-emerald-950/40 rounded-lg transition-colors text-sm font-medium border border-emerald-800/40"><BookOpen className="w-4 h-4 mr-2.5 text-emerald-400" /><span>Workspace & Artifacts</span></button><button onClick={handleGoogleHubClick} className="w-full flex items-center px-3 py-2 text-blue-300 hover:text-blue-200 hover:bg-blue-950/40 rounded-lg transition-colors text-sm font-medium border border-blue-800/40"><Globe className="w-4 h-4 mr-2.5 text-blue-300" /><span>Google Hub</span></button><div className="flex items-center gap-2"><button onClick={handleSettingsClick} className="flex-1 flex items-center px-3 py-2 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-lg transition-colors text-sm font-medium"><Settings className="w-4 h-4 mr-2.5 text-zinc-400" /><span>Settings</span></button><button onClick={onToggleTheme} className="p-2 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-800 transition-colors" title={`Switch to ${theme === 'dark' ? 'Light' : 'Dark'} mode`}>{theme === 'dark' ? <Sun className="w-4 h-4 text-amber-400" /> : <Moon className="w-4 h-4 text-sky-400" />}</button></div></div>
  </aside></div><GoogleHubModal isOpen={googleHubOpen} onClose={() => setGoogleHubOpen(false)} /></>;
};
