import type { GoogleCapabilityDefinition } from './capabilityTypes';

const readAction = (id: string, label: string, description: string) => ({
  id,
  label,
  description,
  kind: 'query' as const,
  effect: 'read' as const,
  confirmation: 'none' as const,
});

const externalAction = (id: string, label: string, description: string) => ({
  id,
  label,
  description,
  kind: 'external' as const,
  effect: 'read' as const,
  confirmation: 'none' as const,
});

export const GOOGLE_HUB_CAPABILITIES: readonly GoogleCapabilityDefinition[] = [
  {
    id: 'gmail',
    version: 1,
    provider: 'google',
    name: 'Gmail',
    description: 'Search and work with email, drafts and messages.',
    category: 'communication',
    iconKey: 'mail',
    panelKey: 'gmail',
    externalUrl: 'https://mail.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['gmail.read'] },
    actions: [
      readAction('gmail.search', 'Search mail', 'Search Gmail messages on demand.'),
      readAction('gmail.unread', 'Show unread', 'Retrieve unread Gmail messages.'),
      readAction('gmail.attachments', 'Show attachments', 'Find Gmail messages with attachments.'),
      { id: 'gmail.compose', label: 'Create draft', description: 'Create a Gmail draft without sending it.', kind: 'create', effect: 'write', requiredCapabilities: ['gmail.compose'], confirmation: 'none' },
      { id: 'gmail.send', label: 'Send message', description: 'Send a Gmail message to an external recipient.', kind: 'external', effect: 'external-write', requiredCapabilities: ['gmail.send'], confirmation: 'user' },
      externalAction('gmail.open', 'Open Gmail', 'Open the full Gmail application for full message editing.'),
    ],
  },
  {
    id: 'calendar',
    version: 1,
    provider: 'google',
    name: 'Calendar',
    description: 'Inspect schedules and manage calendar events.',
    category: 'scheduling',
    iconKey: 'calendar',
    panelKey: 'calendar',
    externalUrl: 'https://calendar.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['calendar.read'] },
    actions: [
      readAction('calendar.upcoming', 'Upcoming', 'Retrieve upcoming calendar events.'),
      readAction('calendar.availability', 'Find availability', 'Inspect calendar availability for a requested period.'),
      { id: 'calendar.create', label: 'Create event', description: 'Create a calendar event.', kind: 'create', effect: 'external-write', requiredCapabilities: ['calendar.write'], confirmation: 'user' },
      externalAction('calendar.open', 'Open Calendar', 'Open the full Google Calendar application.'),
    ],
  },
  {
    id: 'drive',
    version: 1,
    provider: 'google',
    name: 'Drive',
    description: 'Find and open files stored in Google Drive.',
    category: 'files',
    iconKey: 'hard-drive',
    panelKey: 'drive',
    externalUrl: 'https://drive.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['drive.read'] },
    actions: [
      readAction('drive.recent', 'Recent files', 'Retrieve recent Drive files.'),
      readAction('drive.search', 'Search Drive', 'Search Drive for matching files.'),
      externalAction('drive.open', 'Open Drive', 'Open the full Google Drive application.'),
    ],
  },
  {
    id: 'docs',
    version: 1,
    provider: 'google',
    name: 'Docs',
    description: 'Create, inspect and work with Google documents.',
    category: 'documents',
    iconKey: 'file-text',
    panelKey: 'docs',
    externalUrl: 'https://docs.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['docs'] },
    actions: [
      readAction('docs.recent', 'Recent documents', 'Retrieve recent Google documents.'),
      { id: 'docs.create', label: 'Create document', description: 'Create a Google document.', kind: 'create', effect: 'external-write', requiredCapabilities: ['docs'], confirmation: 'user' },
      { id: 'docs.work', label: 'Work with document', description: 'Read or update a selected Google document.', kind: 'update', effect: 'external-write', requiredCapabilities: ['docs'], confirmation: 'user' },
      externalAction('docs.open', 'Open Docs', 'Open the full Google Docs application.'),
    ],
  },
  {
    id: 'sheets',
    version: 1,
    provider: 'google',
    name: 'Sheets',
    description: 'Inspect, create and update Google spreadsheets.',
    category: 'data',
    iconKey: 'table-2',
    panelKey: 'sheets',
    externalUrl: 'https://sheets.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['sheets.read'] },
    actions: [
      readAction('sheets.recent', 'Recent spreadsheets', 'Retrieve recent Google spreadsheets.'),
      readAction('sheets.preview', 'Preview sheet', 'Read a compact selected-sheet preview.'),
      { id: 'sheets.create', label: 'Create spreadsheet', description: 'Create a Google spreadsheet.', kind: 'create', effect: 'external-write', requiredCapabilities: ['sheets.write'], confirmation: 'user' },
      { id: 'sheets.work', label: 'Work with sheet', description: 'Write supported data to a selected Google spreadsheet.', kind: 'update', effect: 'external-write', requiredCapabilities: ['sheets.write'], confirmation: 'user' },
      externalAction('sheets.open', 'Open Sheets', 'Open the full Google Sheets application.'),
    ],
  },
  {
    id: 'tasks',
    version: 1,
    provider: 'google',
    name: 'Tasks',
    description: 'Inspect and manage Google Tasks.',
    category: 'tasks',
    iconKey: 'check-square',
    panelKey: 'tasks',
    externalUrl: 'https://tasks.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['tasks'] },
    actions: [
      readAction('tasks.today', 'Today', 'Retrieve the tasks relevant to today.'),
      readAction('tasks.upcoming', 'Upcoming', 'Retrieve upcoming Google Tasks.'),
      { id: 'tasks.create', label: 'Create task', description: 'Create a Google Task.', kind: 'create', effect: 'external-write', requiredCapabilities: ['tasks'], confirmation: 'user' },
      { id: 'tasks.complete', label: 'Complete task', description: 'Mark a Google Task as completed.', kind: 'update', effect: 'external-write', requiredCapabilities: ['tasks'], confirmation: 'user' },
      externalAction('tasks.open', 'Open Tasks', 'Open the full Google Tasks application.'),
    ],
  },
  {
    id: 'keep',
    version: 1,
    provider: 'google',
    name: 'Keep / Reference',
    description: 'Access Google Keep notes and Elara reference material.',
    category: 'notes',
    iconKey: 'bookmark',
    panelKey: 'keep',
    externalUrl: 'https://keep.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['keep.read'] },
    actions: [
      readAction('keep.recent', 'Recent notes', 'Retrieve recent reference notes.'),
      readAction('keep.search', 'Search notes', 'Search accessible notes.'),
      { id: 'keep.create', label: 'Create note', description: 'Create a note in the supported Keep/reference backend.', kind: 'create', effect: 'external-write', requiredCapabilities: ['keep.write'], confirmation: 'user' },
      externalAction('keep.open', 'Open Keep', 'Open the full Google Keep application.'),
    ],
  },
  {
    id: 'contacts',
    version: 1,
    provider: 'google',
    name: 'Contacts',
    description: 'Search Google contacts for people and contact details.',
    category: 'people',
    iconKey: 'users',
    panelKey: 'contacts',
    externalUrl: 'https://contacts.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['contacts.read'] },
    actions: [
      readAction('contacts.search', 'Search contacts', 'Search accessible Google contacts.'),
      externalAction('contacts.open', 'Open Contacts', 'Open the full Google Contacts application.'),
    ],
  },
  {
    id: 'chat',
    version: 1,
    provider: 'google',
    name: 'Google Chat',
    description: 'Read and send messages in Google Chat spaces.',
    category: 'communication',
    iconKey: 'message-square',
    panelKey: 'chat',
    externalUrl: 'https://chat.google.com/',
    authorization: { mode: 'capability', requiredCapabilities: ['chat.read'] },
    actions: [
      readAction('chat.spaces', 'Show spaces', 'Retrieve accessible Chat spaces.'),
      readAction('chat.messages', 'Show messages', 'Retrieve messages from an accessible Chat space.'),
      { id: 'chat.send', label: 'Send message', description: 'Send a message to a Google Chat space.', kind: 'external', effect: 'external-write', requiredCapabilities: ['chat.send'], confirmation: 'user' },
      externalAction('chat.open', 'Open Chat', 'Open the full Google Chat application.'),
    ],
  },
];
