import React, { useState } from 'react';
import { listChatMessages, listChatSpaces, sendChatMessage, type ChatMessageResult, type ChatSpace } from '../../services/googleChatService';

export function ChatCapabilityPanel({ canRead, canSend, onActivity }: { canRead: boolean; canSend: boolean; onActivity?: (description: string) => void }) {
  const [spaces, setSpaces] = useState<ChatSpace[]>([]);
  const [selected, setSelected] = useState('');
  const [messages, setMessages] = useState<ChatMessageResult[]>([]);
  const [text, setText] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const loadSpaces = async () => { if (!canRead) return; setLoading(true); setError(null); try { const result = await listChatSpaces(20); setSpaces(result.spaces); setSelected(prev => prev || result.spaces[0]?.name || ''); onActivity?.(`Read ${result.spaces.length} Google Chat spaces`); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to read Google Chat.'); } finally { setLoading(false); } };
  const loadMessages = async () => { if (!canRead || !selected) return; setLoading(true); setError(null); try { const result = await listChatMessages(selected, 20); setMessages(result.messages); onActivity?.(`Read ${result.messages.length} Google Chat messages`); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to read chat messages.'); } finally { setLoading(false); } };
  const send = async () => { if (!canSend || !selected || !text.trim()) return; setLoading(true); setError(null); try { const result = await sendChatMessage(selected, text.trim()); setMessages(prev => [result, ...prev]); setText(''); onActivity?.('Sent a Google Chat message'); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to send chat message.'); } finally { setLoading(false); } };
  return <div className="space-y-5"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-white/35">Collaboration</p><h3 className="mt-1 text-lg font-semibold">Google Chat</h3><p className="mt-1 text-sm text-white/50">Inspect spaces and messages, with sending kept behind the explicit chat.send capability.</p></div>{!canRead ? <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.05] p-4 text-sm text-amber-100">Google Chat read access is not enabled.</div> : <><div className="flex flex-wrap gap-2"><button type="button" onClick={() => void loadSpaces()} disabled={loading} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium hover:bg-white/[0.06]">{loading ? 'Loading…' : 'Load spaces'}</button><button type="button" onClick={() => void loadMessages()} disabled={loading || !selected} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium hover:bg-white/[0.06]">Refresh messages</button></div><select value={selected} onChange={e => setSelected(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"><option value="">Select a space…</option>{spaces.map(space => <option key={space.name} value={space.name}>{space.displayName || space.name}</option>)}</select>{error && <div className="rounded-xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-200">{error}</div>}<div className="divide-y divide-white/5 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">{messages.length === 0 ? <div className="px-4 py-8 text-center text-sm text-white/35">No messages loaded yet.</div> : messages.map(message => <div key={message.name} className="px-4 py-3"><p className="text-xs text-white/35">{message.sender || 'User'}</p><p className="mt-1 text-sm text-white/75">{message.text}</p></div>)}</div>{canSend && <div className="flex gap-2"><input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void send(); }} placeholder="Message this space…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none placeholder:text-white/25"/><button type="button" onClick={() => void send()} disabled={loading || !text.trim() || !selected} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium hover:bg-white/[0.06] disabled:opacity-40">Send</button></div>}</>}</div>;
}
