import React, { useState } from 'react';
import { createReferenceNote, searchReferenceNotes, type ReferenceNoteItem } from '../../services/referenceArchiveService';

export function KeepCapabilityPanel({ canRead, canWrite, onActivity }: { canRead: boolean; canWrite: boolean; onActivity?: (description: string, reversible?: boolean) => void }) {
  const [query, setQuery] = useState('');
  const [notes, setNotes] = useState<ReferenceNoteItem[]>([]);
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [error, setError] = useState<string | null>(null);
  const search = async () => { if (!canRead) return; setError(null); try { const result = await searchReferenceNotes(query); setNotes(result.notes); onActivity?.(`Read ${result.notes.length} reference note${result.notes.length === 1 ? '' : 's'}`); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to read reference notes.'); } };
  const create = async () => { if (!canWrite || !title.trim()) return; setError(null); try { const note = await createReferenceNote(title.trim(), content); setNotes(prev => [note, ...prev]); setTitle(''); setContent(''); onActivity?.(`Created reference note “${note.title}”`, true); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create reference note.'); } };
  return <div className="space-y-5"><div><p className="text-xs font-medium uppercase tracking-[0.16em] text-white/35">Notes</p><h3 className="mt-1 text-lg font-semibold">Keep / Reference</h3><p className="mt-1 text-sm text-white/50">A focused reference surface backed by Elara’s existing local archive.</p></div>{!canRead ? <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.05] p-4 text-sm text-amber-100">Keep/reference read access is not enabled.</div> : <><div className="flex gap-2"><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void search(); }} placeholder="Search notes…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm outline-none placeholder:text-white/25"/><button type="button" onClick={() => void search()} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium">Search</button></div>{canWrite && <section className="space-y-2 rounded-2xl border border-white/10 bg-white/[0.03] p-4"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Note title" className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"/><textarea value={content} onChange={e => setContent(e.target.value)} rows={4} placeholder="Reference note…" className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm"/><button type="button" onClick={() => void create()} disabled={!title.trim()} className="rounded-xl border border-white/10 px-4 py-2.5 text-sm font-medium disabled:opacity-40">Create note</button></section>}{error && <div className="rounded-xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-200">{error}</div>}<div className="divide-y divide-white/5 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">{notes.length === 0 ? <div className="px-4 py-8 text-center text-sm text-white/35">No notes loaded yet.</div> : notes.map(note => <article key={note.id} className="px-4 py-4"><p className="text-sm font-medium">{note.title}</p><p className="mt-1 line-clamp-3 whitespace-pre-wrap text-xs leading-5 text-white/50">{note.content}</p>{note.tags.length > 0 && <p className="mt-2 text-[11px] text-white/30">{note.tags.join(' · ')}</p>}</article>)}</div></>}</div>;
}
